# Generated by Django 5.2.1 on 2025-05-19 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jurusan_kelas_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='siswa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.jurusan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.kelas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('izin', 'Izin'), ('alfa', 'Alfa'), ('bolos', 'Bolos')], max_length=10)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('pelanggaran', models.ManyToManyField(to='core.masterpelanggaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.siswa')),
            ],
        ),
    ]
